title: Samantha Hartwell is a girl boss

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

github:
  reposiory_url: https://github.com/criswell/samantha-llm
